language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

install: /bin/true

script: ./gradlew clean build --refresh-dependencies
